- name: print vars
  hosts: local
  connection: local
  vars_file:
  - 06.course.yaml
  tasks:
    - name: print vars
      vars:
        Course: aws
      ansible.builtin.debug:
        msg: "Course name is: {{ Course }} and Trainer is : {{ Trainer }} duration is {{ Duration }}"
