- name: print user and pass
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your password?
  tasks:
  - name: print
    ansible.builtin.debug:
      msg: "my nam is {{ username }} and pass is {{ password }}"