- name: print vars
  hosts: local
  vars_files:
  - 06.course.yaml
  tasks:
    - name: print vars
      vars:
        Course: from task level
      ansible.builtin.debug:
        msg: "curr sub is : {{ Course }}"
    - name: print vars
      ansible.builtin.debug:
        msg: "curr sub is : {{ Course }}"
