- name: print vars
  hosts: local
  vars_files:
  - 06.course.yaml
  tasks:
    - name: print vars from task level
      vars:
        Course: from task level
      ansible.builtin.debug:
        msg: "curr sub is : {{ Course }}"
    - name: print vars from folder
      ansible.builtin.debug:
        msg: "curr sub is : {{ Course }}"
    - name: print vars from INV which not mention in taks and var_folder
      ansible.builtin.debug:
        msg: "curr sub is : {{ sub }}"
