- name: data types
  hosts: local
  connection: local
  vars:
    PROGRAME: "AWS Devops" # string
    DURATION: 140 # int 
    IS_LIVE: true  # bool 
    DETAILS:    # dictinary/maps 
      TRAINER: "shiva"
      MONTHS: 4
    TOPIC:   # list
    - linux
    - AWS
    - Ansible
    - terrafrom
    - Docker
    - Kubernetes
  tasks:
  - name: print vars
    ansible.builtin.debug:
      msg: |
        Program: {{ PROGRAME }}
        Duration: {{ DURATION }}
        Ruuning_topic_now: {{ TOPIC[2] }}
        details: {{ DETAILS.MONTHS }} 
