- name: print vars
  hosts: local
  connection: local
  vars:
    Course_duration: 10
    Trainer_live: true
  tasks:
    - name: print vars
      ansible.builtin.debug:
        msg: "Course name duration"
      when:  Course_duration = 10
    - name: print vars
      ansible.builtin.debug:
        msg: "training is live "
      when:  Trainer_live   


