- name: ansible command vs ansile shell
  hosts: local
  connection: local
  tasks:
  - name: command and shell module test
    # ansible.builtin.commoad: cat /etc/passwd | grep root
    ansible.bultin.shell: cat /etc/passwd | grep root
    register: user_output