- name: doing on loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:  # list of string
    - nginx
    - mysql
    - git
    - httpd