- name: doing on loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:   # list of map
    - { name: "nginx", state: "absent"}
    - { name: "mysql", state: "absent"}
    - { name: "git", state: "absent"}
    - { name: "httpd", state: "absent"}