- name: doing on loops
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, docker
    tags:
      name: devops
      project: roboshop
      componenet: catalogue
  tasks:
  - name: debug filters
    ansible.builtin.debug:
      msg: "Hi shiva, {{ GREETING | default('GOOD Morning') }}"  # deafult filter

  - name: convertion of strings to list
    ansible.builtin.debug:
      msg: "{{ topics | split (',') }}"  # convertion of strings to list

  - name: convertion of maps  to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"
    register: user_output

  - name: print convertion of maps  to list
    ansible.builtin.debug:
      msg: "{{ user_output }}"
    
  